config/routes.rb
Rails.application.routes.draw do
  resources :inboxes
  # get 'invoices/index'
  # get 'invoices/show'
  root to: 'invoices#index'
  resources :invoices, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord

     def self.ransackable_attributes(auth_object = nil )
        %w(full_name)
     end

	 has_one_attached :pdf_file

	 has_many :invoice_items, dependent: :destroy

	 before_save :set_default_discount

	  private

	  def set_default_discount
	    self.discount ||= 0
	  end

    STATUS_CLASS = {
        :draft => "badge badge-secondary",
        :sent => "badge badge-primary",
        :paid => "badge badge-success"
    }

    def subtotal
        self.invoice_items.map { |item| item.qty * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.discount / 100.0)
    end

    def vat_calculated
        (subtotal - discount_calculated) * (self.vat / 100.0)
    end

    def total
        subtotal - discount_calculated + vat_calculated
    end

    def status_class
        STATUS_CLASS[self.status.to_sym]
    end
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	    include Pagy::Backend

end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: [:show, :edit, :update, :destroy]

  # GET /inboxes
  # GET /inboxes.json
    def index
    @q = Inbox.ransack(params[:q])
    @inboxes = @q.result(distinct: true)
  end

  # GET /inboxes/1
  # GET /inboxes/1.json
  def show
  end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit
  end

  # POST /inboxes
  # POST /inboxes.json
  def create
    @inbox = Inbox.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to @inbox, notice: 'Inbox was successfully created.' }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1
  # PATCH/PUT /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to @inbox, notice: 'Inbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1
  # DELETE /inboxes/1.json
  def destroy
    @inbox.destroy
    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: 'Inbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbox
      @inbox = Inbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inbox_params
      params.require(:inbox).permit(:name)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    def new 
      @invoice = Invoice.new
    end 

   # def index
   #   @q = Invoice.ransack(params[:q])
   #   @invoices = @q.result(distinct: true)
   #    per_page = 5
   #    #  @invoices = scope

   #    # @invoices = Invoice.all
   #    # @pagy, @invoices = pagy(Invoice.all)
   #    total_invoices = @invoices.count
   #    if total_invoices > per_page
   #      @pagy, @invoices = pagy(@invoices, items: per_page)
   #    end
   #  end

   def index
      # debugger
      @q = Invoice.ransack(params[:q])
      @invoices = @q.result(distinct: true)
      per_page = 5
      @pagy, @invoices = pagy(@invoices, items: per_page)
  end

  #  def index
  #  #    debugger
  #   @pagy, @invoices = pagy(Invoice.all)
  # end
      


     def create
        @invoice = Invoice.new(invoice_params)
        if @invoice.save
          redirect_to @invoice, notice: 'Invoice was successfully created.'
        else
          render :new
        end  
     end


    def show
        @invoice = Invoice.find(params[:id])
        if @invoice
        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice No. #{@invoice.id}",
                page_size: 'A4',
                template: "invoices/show.html.erb",
                layout: "pdf.html",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
            end
        end
        else
        redirect_to invoices_path, alert: 'Invoice not found.'
     end
    end

    private
        def scope
            ::Invoice.all.includes(:invoice_items)
        end

    def invoice_params
     params.require(:invoice).permit(:full_name, :address, :name, :email, :phone, :status, :discount, :pdf_file)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pagination.rb
module PaginationHelper

  # include Pagy::Frontend

end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox, local: true) do |form| %>
  <% if inbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
        <% inbox.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/edit.html.erb
<h1>Editing Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Show', @inbox %> |
<%= link_to 'Back', inboxes_path %>

app/views/inboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inboxes</h1>

<br>
<%= search_form_for @q do |f| %>
<%= f.label :name_cont %>
<%= f.search_field :name_cont %>
 <%= f.submit %>
<% end %>

<%= sort_link @q, :messages_count, 'Popular' %>
<%= sort_link @q, :created_at, 'Fresh' %>

<%= link_to 'Clear search', request.path if request.query_parameters.any? %>

app/views/inboxes/new.html.erb
<h1>New Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Back', inboxes_path %>

app/views/inboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inbox.name %>
</p>

<%= link_to 'Edit', edit_inbox_path(@inbox) %> |
<%= link_to 'Back', inboxes_path %>

app/views/invoices/index.html.erb
<!-- app/views/invoices/index.html.erb -->

<h1>All Invoices</h1>

<%= link_to 'New Invoice', new_invoice_path, class: 'btn btn-warning' %>

<%= search_form_for @q do |f| %>
  <%= f.label :full_name_cont %>
  <%= f.search_field :full_name_cont %>
  <%= f.submit %>
<% end %>


<%= sort_link @q, :messages_count, 'Popular' %>
<%= sort_link @q, :created_at, 'Fresh' %>

<%= link_to 'Clear search', request.path if request.query_parameters.any? %>


<div class="card mb-4">
<table class="table table-bordered border-primary table-hover ">
  <thead>
    <tr>
      <th>Invoice ID</th>
       <th>Full_name</th>
       <th>Address</th>
       <th>Email</th>
       <th>Phone</th>
      <th>Status</th>
      <th>PDF FILE</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td class="table-primary"><%= invoice.id %></td>
      	<td class="table-secondary"><%= invoice.full_name %></td>
      	<td class="table-info"><%= invoice.address %></td>
      	<td class="table-danger"><%= invoice.email %></td>
      	<td class="table-secondary"><%= invoice.phone %></td>
        <td class="table-warning"><%= invoice.status %></td>

        <td>
            <% if invoice.pdf_file.attached? %>
                <iframe src="<%= rails_blob_path(invoice.pdf_file, disposition: 'inline') %>" width="100" height="80" frameborder="0"></iframe>

            <% else %>
              No PDF file attached
            <% end %>
        </td>

        <td>
          <%= link_to 'View', invoice_path(invoice),class: 'btn btn-danger' %>
          <%= link_to 'Download PDF', invoice_path(invoice, format: :pdf),class: 'btn btn-secondary' %>
          <!-- Add more actions if needed -->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex justify-content-center"><%= pagy_bootstrap_nav(@pagy).html_safe %></div>

</div>

app/views/invoices/new.html.erb
<!-- app/views/invoices/new.html.erb -->

<h1>New Invoice</h1>

<%= form_with(model: @invoice, url: invoices_path, method: :post) do |form| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% @invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-mdb-input-init class="form-outline mb-4">
    <%= form.label :full_name %>
    <%= form.text_field :full_name, id: "form1Example1",class: "form-control" %>
  </div>

  <div data-mdb-input-init class="form-outline mb-4">
    <%= form.label :email %>
    <%= form.text_field :email,id: "form1Example1",class: "form-control" %>
  </div>


  <div data-mdb-input-init class="form-outline mb-4">
      <%= form.label :name %>
      <%= form.text_field :name,id: "form1Example1",class: "form-control" %>
   </div>

  <div data-mdb-input-init class="form-outline mb-4">
      <%= form.label :phone %>
      <%= form.text_field :phone,id: "form1Example1",class: "form-control" %>
    </div>

    
  <div data-mdb-input-init class="form-outline mb-4">
      <%= form.label :address %>
      <%= form.text_field :address,id: "form1Example1",class: "form-control" %>
    </div>


    
  <div data-mdb-input-init class="form-outline mb-4">
      <%= form.label :status %>
      <%= form.text_field :status,id: "form1Example1",class: "form-control" %>
    </div>


   
  <div data-mdb-input-init class="form-outline mb-4">
      <%= form.label :pdf_file, 'PDF File' %>
      <%= form.file_field :pdf_file %>
     </div>


    <div class="actions">
      <%= form.submit 'Create Invoice' %>
    </div>

  <% end %>

<%= link_to 'Back', invoices_path, class: 'btn btn-primary'%>

app/views/invoices/show.html.erb
<!-- app/views/invoices/show.html.erb -->

<h1>Invoice Details</h1>

<div>
	 
  <strong>Invoice ID:</strong> <%= @invoice.id %><br>
  <strong>FullName:</strong> <%= @invoice.full_name %><br>
  <strong>Address</strong> <%= @invoice.address %><br>
  <strong>Email</strong> <%= @invoice.email %><br>
  <strong>Contact No.</strong><%= @invoice.phone %><br>
  <strong>Status:</strong> <%= @invoice.status %><br>
  <strong>Pdf_File:</strong> 
  <% if @invoice.pdf_file.attached? %>
  <iframe src="<%= rails_blob_path(@invoice.pdf_file, disposition: 'inline') %>" width="100" height="80" frameborder="0"></iframe>
	<% else %>
	  <p>No PDF file attached</p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGeneratePdf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
    <h2>Hello</h2>
    <%= yield %>
</body>
</html>

app/views/layouts/shared/_header.html.erb
<%= link_to ‘DOWNLOAD PDF’, invoice_path(@invoice, format: :pdf) %>